branches:
- main
pulls: true
projects:
  Shopkeepers:
    path: ""
    icon: plugin_logo.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.1
        branch: pm5
      - src: Himbeer/LibSkin/LibSkin
        version: ^2.0.0
        branch: master