#
# Shopkeepers v0.9.1 by FoxWorm3365
# (C) 2023-now FoxWorn3365
# 
# Relased under the GPL-3.0 license 
# https://github.com/FoxWorn3365/Shopkeepers/blob/main/LICENSE
#

enabled: true

# Max shopkeeper's entities for one player (PER SHOP)
max-entities-for-player: 5
# Player that can bypass this limitation
max-entities-bypass:
  - YourMinecraftUsername

# Moderation settings   - THIS IS A CONTAIN CONDITION so if you set 'pro' also names like 'apron', 'prototypus', 'proto', 'pro' and it's case INSENSITIVE
banned-shop-names: # Banned shop names, array
  - hitler
  - nazi