name: Shopkeepers
version: 1.2.0
api: 5.0.0

main: FoxWorn3365\Shopkeepers\Core
author: FoxWorn3365
website: https://github.com/FoxWorn3365/Shopkeepers
description: Add shopkeepers to your PocketMine server!

commands:
  shopkeepers:
    description: The main shopkeepers command
    usage: "/shopkeepers [list|create|summon|rename|edit|info|history|trade] [<NAME>] [...]"
    aliases:
      - sk
      - shopk
      - skeepers
    permission: shopkeepers.base
    permission-message: "You do not have permission to use the base command!"

permissions:
  shopkeepers.base:
    description: "Allows users to use the base command"
    default: true
  shopkeepers.shop.summon:
    description: "Allows users to summon player's shop"
    default: true
  shopkeepers.shop.create:
    description: "Allow users to create a shop"
    default: true
  shopkeepers.shop.edit:
    description: "Allow users to edit they'r shop"
    default: true
  shopkeepers.shop.list:
    description: "Allow users to see a list of their shops"
    default: true
  shopkeepers.shop.remove:
    description: "Allow users to despawn they'r Villager shops"
    default: true
  shopkeepers.shop.rename:
    descritpion: "Allow users to rename they'r shops"
    default: true
  shopkeepers.shop.namevisible:
    description: "Allow users to decide if the shopkepeer's name should be visible or no"
    default: true
  shopkeepers.shop.history:
    description: "Allow users to view the trade history of his Shopkeepers"
    default: true
  shopkeepers.shop.enableDisable:
    description: "Allow users to enable and disable their own Shopkeepers from the menu"
    default: true
  shopkeepers.shop.admin:
    description: "Allows users to decide if the shopkeepers should be admin or none"
    default: op
  shopkeepers.shop.kill:
    description: "Allow users to kill every shopkeepers, also of other players"
    default: op
  shopkeepers.shop.defaultGUI:
    description: "Allow users to see and use the /sk command without args to open the base GUI"
    default: true
  shopkeepers.shop.use:
    description: "Allow users to use a shopkeeper when they touch it"
    default: true
  shopkeepers.shop.allowRemoteInventoryOpen:
    description: "Allow users to open a shopkeeper's inventory with the command /sk inventory"
    default: op
  shopkeepers.shop.allowRemoteTrade:
    description: "Allow users to remotely trade with a shopkeeper with the command /sk trade <author> <shop>"
    default: true